/**
 * OmenHosting — Whole-panel state persistence
 *
 * Replit's filesystem is ephemeral across redeploys: every "republish" wipes
 * accounts (mcsmanager/web/data), the daemon's own identity (its Config), and
 * every instance's config and world data. bootstrap-admin.js already works
 * around the accounts/identity half by recreating them deterministically at
 * every boot — but a Minecraft world isn't deterministic. It has to actually
 * survive, which means it has to live somewhere that isn't this filesystem.
 *
 * This module snapshots the directories that can't be regenerated to
 * whatever S3-compatible bucket BACKUP_PROVIDER=s3 (or b2) points at, and
 * restores them before anything else boots. It's a separate concern from
 * backup/manager.js, which backs up one running instance's world on a
 * schedule for disaster recovery — this is "does the panel still have any
 * data at all after a redeploy."
 *
 * Layout on the remote (three independent archives, not one, so a huge
 * InstanceData snapshot doesn't block restoring accounts or configs first):
 *   <STATE_SYNC_ROOT>/web-data.zip        mcsmanager/web/data
 *   <STATE_SYNC_ROOT>/instance-config.zip mcsmanager/daemon/data/InstanceConfig
 *   <STATE_SYNC_ROOT>/instance-data.zip   mcsmanager/daemon/data/InstanceData
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { createProvider } = require('./storage/index');
const { createZip, extractZip, DEFAULT_EXCLUDES } = require('./backup/archive');

const BASE_DIR = path.resolve(__dirname, '..');
const STATE_SYNC_ROOT = process.env.STATE_SYNC_ROOT || 'omen-panel-state';

/**
 * A save/restore that silently no-ops (unconfigured) or silently fails
 * (network error at 3am) is indistinguishable from "working" until someone
 * loses data on a redeploy and asks why — which is exactly what happened
 * here: the bucket turned out to be completely empty with no earlier signal
 * anywhere accessible short of an engineer manually listing it. This file
 * is the accessible signal — read via GET /api/omen/state-sync/status.
 */
const STATUS_FILE = path.join(BASE_DIR, 'omen-data', 'state-sync-status.json');

function writeStatus(patch) {
  let status = {};
  try { status = JSON.parse(fs.readFileSync(STATUS_FILE, 'utf8')); } catch { /* first write */ }
  status = { ...status, ...patch };
  try {
    fs.mkdirSync(path.dirname(STATUS_FILE), { recursive: true });
    fs.writeFileSync(STATUS_FILE, JSON.stringify(status, null, 2));
  } catch (err) {
    console.error('[state-sync] Could not write status file:', err.message);
  }
  return status;
}

function getStatus() {
  const kind = (process.env.BACKUP_PROVIDER || 'local').toLowerCase();
  const configured = kind === 's3' || kind === 'b2';
  let persisted = {};
  try { persisted = JSON.parse(fs.readFileSync(STATUS_FILE, 'utf8')); } catch { /* never run yet */ }
  return { configured, provider: configured ? kind : null, ...persisted };
}

const TARGETS = [
  {
    key: 'web-data.zip',
    dir: path.join(BASE_DIR, 'mcsmanager/web/data'),
    excludes: []
  },
  {
    key: 'instance-config.zip',
    dir: path.join(BASE_DIR, 'mcsmanager/daemon/data/InstanceConfig'),
    excludes: []
  },
  {
    key: 'instance-data.zip',
    // The actual Minecraft worlds, plugins, and jars — the thing "keep
    // everything" actually means. Same excludes as per-instance backups:
    // logs/caches/libraries are regenerated by the server on next start.
    dir: path.join(BASE_DIR, 'mcsmanager/daemon/data/InstanceData'),
    excludes: DEFAULT_EXCLUDES
  }
];

/**
 * Resolves the configured provider, or null if state sync isn't set up.
 * Deliberately non-fatal: a local/dev setup without any BACKUP_PROVIDER
 * secrets configured should keep working exactly as before.
 */
function resolveProvider() {
  const kind = (process.env.BACKUP_PROVIDER || 'local').toLowerCase();
  if (kind !== 's3' && kind !== 'b2') return null;
  try {
    const { provider } = createProvider({ dataDir: path.join(BASE_DIR, 'omen-data') });
    // createProvider() applies BACKUP_REMOTE_ROOT as the prefix; state sync
    // needs its own, separate root so it never collides with per-instance
    // world backups sharing the same bucket.
    provider.cfg.remoteRoot = STATE_SYNC_ROOT;
    return provider;
  } catch (err) {
    console.warn(`[state-sync] Provider misconfigured, skipping: ${err.message}`);
    return null;
  }
}

async function restoreState() {
  const provider = resolveProvider();
  if (!provider) {
    console.log('[state-sync] No S3/B2 provider configured (BACKUP_PROVIDER is not "s3" or "b2") — starting with whatever local data exists. Check GET /api/omen/state-sync/status.');
    return;
  }

  const restored = {};
  try {
    await provider.init();
  } catch (err) {
    console.error('[state-sync] Provider failed to initialize, cannot restore:', err.message);
    writeStatus({ lastRestoreAt: Date.now(), lastRestoreError: err.message });
    return;
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omen-restore-'));
  try {
    for (const target of TARGETS) {
      const remotePath = '/' + target.key;
      const localZip = path.join(tmpDir, target.key);

      let found = true;
      try {
        await provider.download(remotePath, localZip);
      } catch (err) {
        found = false;
        console.log(`[state-sync] No saved ${target.key} yet (${err.message}) — starting fresh.`);
      }
      if (!found) continue;

      fs.mkdirSync(target.dir, { recursive: true });
      const { entries } = await extractZip(localZip, target.dir);
      console.log(`[state-sync] Restored ${target.key} → ${path.relative(BASE_DIR, target.dir)} (${entries} entries)`);
      restored[target.key] = entries;
    }
    writeStatus({ lastRestoreAt: Date.now(), lastRestoreError: null, restored });
  } catch (err) {
    console.error('[state-sync] Restore failed:', err.message);
    writeStatus({ lastRestoreAt: Date.now(), lastRestoreError: err.message });
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

async function saveState() {
  const provider = resolveProvider();
  if (!provider) {
    // Runs unconditionally from a timer/shutdown trap regardless of whether
    // state sync is configured — record *why* nothing happened so that's
    // visible without cross-referencing deployment logs.
    writeStatus({ lastSaveAt: Date.now(), lastSaveError: 'BACKUP_PROVIDER is not "s3" or "b2" — state sync is not configured' });
    return;
  }

  try {
    await provider.init();
  } catch (err) {
    console.error('[state-sync] Provider failed to initialize, cannot save:', err.message);
    writeStatus({ lastSaveAt: Date.now(), lastSaveError: err.message });
    return;
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omen-save-'));
  const saved = {};
  try {
    for (const target of TARGETS) {
      if (!fs.existsSync(target.dir) || fs.readdirSync(target.dir).length === 0) continue;

      const localZip = path.join(tmpDir, target.key);
      const { size, entries } = await createZip(target.dir, localZip, { excludes: target.excludes });
      await provider.upload(localZip, '/' + target.key);
      console.log(`[state-sync] Saved ${target.key} (${entries} entries, ${(size / 1024 / 1024).toFixed(1)} MB)`);
      saved[target.key] = { entries, sizeMB: Number((size / 1024 / 1024).toFixed(1)) };
      fs.rmSync(localZip, { force: true });
    }
    writeStatus({ lastSaveAt: Date.now(), lastSaveError: null, saved });
  } catch (err) {
    console.error('[state-sync] Save failed:', err.message);
    writeStatus({ lastSaveAt: Date.now(), lastSaveError: err.message });
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

module.exports = { restoreState, saveState, resolveProvider, getStatus, TARGETS, STATE_SYNC_ROOT };
