/**
 * OmenHosting — Whole-panel state persistence
 *
 * Replit's filesystem is ephemeral across redeploys: every "republish" wipes
 * accounts (mcsmanager/web/data), the daemon's own identity (its Config), and
 * every instance's config and world data. bootstrap-admin.js already works
 * around the accounts/identity half by recreating them deterministically at
 * every boot — but a Minecraft world isn't deterministic. It has to actually
 * survive, which means it has to live somewhere that isn't this filesystem.
 *
 * This module snapshots the directories that can't be regenerated to
 * whatever S3-compatible bucket BACKUP_PROVIDER=s3 (or b2) points at, and
 * restores them before anything else boots. It's a separate concern from
 * backup/manager.js, which backs up one running instance's world on a
 * schedule for disaster recovery — this is "does the panel still have any
 * data at all after a redeploy."
 *
 * Layout on the remote (three independent archives, not one, so a huge
 * InstanceData snapshot doesn't block restoring accounts or configs first):
 *   <STATE_SYNC_ROOT>/web-data.zip        mcsmanager/web/data
 *   <STATE_SYNC_ROOT>/instance-config.zip mcsmanager/daemon/data/InstanceConfig
 *   <STATE_SYNC_ROOT>/instance-data.zip   mcsmanager/daemon/data/InstanceData
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { createProvider } = require('./storage/index');
const { createZip, extractZip, DEFAULT_EXCLUDES } = require('./backup/archive');

const BASE_DIR = path.resolve(__dirname, '..');
const STATE_SYNC_ROOT = process.env.STATE_SYNC_ROOT || 'omen-panel-state';

const TARGETS = [
  {
    key: 'web-data.zip',
    dir: path.join(BASE_DIR, 'mcsmanager/web/data'),
    excludes: []
  },
  {
    key: 'instance-config.zip',
    dir: path.join(BASE_DIR, 'mcsmanager/daemon/data/InstanceConfig'),
    excludes: []
  },
  {
    key: 'instance-data.zip',
    // The actual Minecraft worlds, plugins, and jars — the thing "keep
    // everything" actually means. Same excludes as per-instance backups:
    // logs/caches/libraries are regenerated by the server on next start.
    dir: path.join(BASE_DIR, 'mcsmanager/daemon/data/InstanceData'),
    excludes: DEFAULT_EXCLUDES
  }
];

/**
 * Resolves the configured provider, or null if state sync isn't set up.
 * Deliberately non-fatal: a local/dev setup without any BACKUP_PROVIDER
 * secrets configured should keep working exactly as before.
 */
function resolveProvider() {
  const kind = (process.env.BACKUP_PROVIDER || 'local').toLowerCase();
  if (kind !== 's3' && kind !== 'b2') return null;
  try {
    const { provider } = createProvider({ dataDir: path.join(BASE_DIR, 'omen-data') });
    // createProvider() applies BACKUP_REMOTE_ROOT as the prefix; state sync
    // needs its own, separate root so it never collides with per-instance
    // world backups sharing the same bucket.
    provider.cfg.remoteRoot = STATE_SYNC_ROOT;
    return provider;
  } catch (err) {
    console.warn(`[state-sync] Provider misconfigured, skipping: ${err.message}`);
    return null;
  }
}

async function restoreState() {
  const provider = resolveProvider();
  if (!provider) {
    console.log('[state-sync] No S3/B2 provider configured — starting with whatever local data exists.');
    return;
  }

  await provider.init();
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omen-restore-'));

  try {
    for (const target of TARGETS) {
      const remotePath = '/' + target.key;
      const localZip = path.join(tmpDir, target.key);

      let found = true;
      try {
        await provider.download(remotePath, localZip);
      } catch (err) {
        found = false;
        console.log(`[state-sync] No saved ${target.key} yet (${err.message}) — starting fresh.`);
      }
      if (!found) continue;

      fs.mkdirSync(target.dir, { recursive: true });
      const { entries } = await extractZip(localZip, target.dir);
      console.log(`[state-sync] Restored ${target.key} → ${path.relative(BASE_DIR, target.dir)} (${entries} entries)`);
    }
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

async function saveState() {
  const provider = resolveProvider();
  if (!provider) return;   // silently a no-op — this runs unconditionally from a timer/trap

  await provider.init();
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omen-save-'));

  try {
    for (const target of TARGETS) {
      if (!fs.existsSync(target.dir) || fs.readdirSync(target.dir).length === 0) continue;

      const localZip = path.join(tmpDir, target.key);
      const { size, entries } = await createZip(target.dir, localZip, { excludes: target.excludes });
      await provider.upload(localZip, '/' + target.key);
      console.log(`[state-sync] Saved ${target.key} (${entries} entries, ${(size / 1024 / 1024).toFixed(1)} MB)`);
      fs.rmSync(localZip, { force: true });
    }
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
}

module.exports = { restoreState, saveState, resolveProvider, TARGETS, STATE_SYNC_ROOT };
